config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  get '/contact', to: 'pages#contact'
  get '/legal', to: 'pages#legal'
  get '/about', to: 'pages#about'
  get '/terms_of_use', to: 'pages#terms_of_use'
  get '/privacy_policy', to: 'pages#privacy_policy'

  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :articles
  resources :contacts
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  
  belongs_to :user

  validates :title, presence: true, uniqueness: true, length: {minimum: 10, maximum: 60 }
  validates :description, presence: true, length: { minimum: 130, maximum: 160 }
  validates :content, presence: true
  validates :image, presence: true, length: {minimum: 3, maximum: 100 }

end

app/models/contact.rb
class Contact < ActiveRecord::Base 
    
validates :name, presence: true
validates :email, presence: true
validates :comments, presence: true

end 

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :articles

  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true
  validates_format_of :email, :with => /\A(\S+)@(.+)\.(\S+)\z/
  validates :boolean_field_name, inclusion: { in: [true, false] }
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action."
      redirect_to articles_path
    end
  end
  
  def require_admin
    if !current_user.admin?
      flash[:danger] = "You must be an admin to perform that action."
      redirect_to articles_path
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_articles, only: [:index, :show]
  before_action :require_user, except: [:show, :index]
  before_action :require_admin, except: [:show, :index]

  # GET /articles
  # GET /articles.json
  def index
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_path, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find_by_title(params[:id])
    end
    
    def set_articles
      @articles = Article.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :description, :image)
    end
    
    def to_param
      "#{title}"
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
def create
  @contact = Contact.new(contact_params)
    
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      comments = params[:contact][:comments]
      flash[:success] = 'Message sent.'
      redirect_to new_contact_path
    else
      flash[:danger] = 'Error occured, message has not been sent.'
      redirect_to new_contact_path
    end
    
end
  
  private
    def contact_params
      # "white listing" these parameters
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      
      session[:user_id] = user.id
      flash[:success] = "Welcome #{user.username}! You are now logged in."
      redirect_to articles_path
      
    else
      flash.now[:danger] = "Your email address or password does not match."
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You are now logged out."
    redirect_to root_path
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   
   def home
   end
   
   def about
   end
   
   def contact
   end
   
   def legal
   end
   
   def privacy_policy
   end
   
   def terms_of_use
   end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <div class="row">
    <div class="col s12 m6 offset-m3">
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
    
          <ul>
          <% @article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="input-field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div class="input-field">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "materialize-textarea" %>
      </div>
      <div class="input-field">
        <%= f.label :content %><br>
        <%= f.text_area :content, class: "materialize-textarea" %>
        
        Learn what to do with your bees in winter, spring, summer, and fall with these helpful tips and techniques that will get you beekeeping like an expert.
        
      </div>
      <div class="input-field">
        <%= f.label :image %><br>
        <%= f.text_field :image %>
      </div>
      <div class="actions center">
        <%= f.submit class: "btn waves-effect waves-light green" %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<section class="article-font">
  
  <!--Intro Card-->
  <div class="row">
    <div class="col s12 m10 offset-m1 l6 offset-l3">
      <div class="card green">
        <div class="card-content white-text center">
          <div class="card-title">
            Welcome!
          </div>
          <p>Here you can find all the articles on how to become a beekeeper.</p>
        </div>
      </div>
    </div>
  </div>
  
  <!--Cards-->
  <% @articles.sort_by{|item| item.created_at}.reverse.each do |article| %>
    <div class="row">
      <div class="col s12 m8 offset-m2 l4 offset-l4">
        <div class="card orange">
          <!--Image-->
          <div class="card-image waves-effect waves-block waves-light">
            <%= link_to image_tag(article.image), article_path(article.title) %>
          </div>
          <div class="card-content white-text center">
            <span class="card-title">
              <!--Title-->
              <%= link_to article.title, article_path(article.title) %>
            </span>
            <!--Date-->
            <p><%= link_to article.description, article_path(article.title) %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  
</section>

app/views/articles/new.html.erb
<h2 class="center orange-text">New Article</h2>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<section class="article">
  <p id="notice"><%= notice %></p>
  
  <div class="row">
    <div class="col s12 m8 offset-m2 l6 offset-l3">
      <p class="center"><%= link_to 'Back to Articles', articles_path, class: "btn waves-effect waves-light indigo" %></p>
      <h2 class="center orange-text"><%= @article.title %></h2>
      <div class="center">
        <%= image_tag(@article.image, class: "article-image responsive-img z-depth-1") %>
      </div>
      <section class="article-content flow-text">
        <%= @article.content.html_safe %>
      </section>
    </div>
  </div>
</section>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <div class="row">
    <div class="col s12 m6 offset-m3">
      <% if @contact.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this blog from being saved:</h2>
    
          <ul>
          <% @contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="input-field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      
      <div class="input-field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      
      <div class="input-field">
        <%= f.label :comments %><br>
        <%= f.text_area :comments, class: "materialize-textarea" %>
      </div>
      
      <button class="waves-effect waves-light btn-large" type="submit" name="action">Send Message</button>
    </div>
  </div>
<% end %>

app/views/contacts/new.html.erb
<div class="center">
  <h1>Leave a Message</h1>
  
  <p>Feel free to get in touch!</p>

  <%= render 'form' %>

  <p><%= link_to 'Back', root_path %></p>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer amber">
  <div class="container">
    
    <div class="row">
      <!--First Column Footer-->
      <div class="col s12 l4 center footer-buttons">
        <ul>
          <li><%= link_to "Articles", articles_path, class: "btn waves-effect waves-light amber darken-4 white-text" %></li>
          <li><%= link_to "About", about_path, class: "btn waves-effect waves-light amber darken-4 white-text" %></li>
        </ul>
      </div>
      
      <!--Social Media-->
      <div class="col s12 l4 center social-media">
        <!--Facebook Link-->
        <%= link_to "https://www.facebook.com/How-2-Bee-442695985906764/" do %>
          <i class="fa fa-facebook fa-2x btn-floating btn-large waves-effect waves-light black"></i>
        <% end %>
        
        <!--Linkedin Link-->
        <%= link_to 'https://www.linkedin.com/company/how-2-bee' do %>
          <i class="fa fa-linkedin fa-2x btn-floating btn-large waves-effect waves-light black"></i>
        <% end %>
        
        <!--Twitter Link-->
        <%= link_to 'https://twitter.com/How_2_Bee' do %>
          <i class="fa fa-twitter fa-2x btn-floating btn-large waves-effect waves-light black"></i>
        <% end %>
        
        <!--Google+ Link-->
        <%= link_to 'https://www.google.com/+How2beeGP' do %>
          <i class="fa fa-google-plus fa-2x btn-floating btn-large waves-effect waves-light black"></i>
        <% end %>
        
        <!--Pinterest Link-->
        <%= link_to 'https://pinterest.com/how2beepin/' do %>
          <i class="fa fa-pinterest fa-2x btn-floating btn-large waves-effect waves-light black"></i>
        <% end %>
      </div>
      
      <!--Second Column Footer-->
      <div class="col s12 l4 center footer-buttons">
        <ul>
          <li><%= link_to "Contact", contact_path, class: "btn waves-effect waves-light amber darken-4 white-text" %></li>
          <li><%= link_to "Legal", legal_path, class: "btn waves-effect waves-light amber darken-4 white-text" %></li>
        </ul>
      </div>
    </div>
    
    </div>
  </div>
  
  <div class="footer-copyright amber darken-4 center">
    <div class="container">
      Copyright &copy; 2016. Made by <%= link_to "Kelsonic", "http://www.kelsonic.io", class: "black-text" %>.
    </div>
  </div>
  
</footer>

app/views/layouts/_head.html.erb
<title>How 2 Bee</title>
<!--Import Google ABeeZee Font-->
<link href='https://fonts.googleapis.com/css?family=ABeeZee' rel='stylesheet' type='text/css'>
<!--Font Awesome-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= csrf_meta_tags %>
<!--Let browser know website is optimized for mobile-->
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

app/views/layouts/_nav.html.erb
<nav>
  <div class="nav-wrapper amber darken-2">
    <div class="brand-logo center">
      <%= link_to "How 2 Bee", root_path, class: "logo-text" %>
      <%= link_to image_tag("LogoIcon.png", class: "logo-icon"), root_path %>
    </div>
    <a class="button-collapse" data-activates="mobile-demo" href="#"><i class="fa fa-bars"></i></a>
    <ul class="right hide-on-med-and-down">
      <% if current_user %>
        <li class="user-nav">Welcome <span class="black-text"><%= current_user.username %></span>
        <%= " | Admin" if current_user.admin? %></li>
      <% end %>
      <li><%= link_to "Articles", articles_path %></li>
      <li><%= link_to "Contact", new_contact_path %></li>
    </ul>
    <ul id="mobile-demo" class="side-nav" style="left: -250px;">
      <% if current_user %>
        <li>Welcome <span class="black-text"><%= current_user.username %></span>
        <%= " | Admin" if current_user.admin? %></li>
      <% end %>
      <li><%= link_to "Articles", articles_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/head' %>
</head>
<body>
  
  <%= render 'layouts/nav' %>
  
  <main>
    <%= render 'layouts/notices' %>
    <%= yield %>
  </main>
  
  <%= render 'layouts/footer' %>
  
  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <%= javascript_include_tag 'application' %>
  
</body>
</html>

app/views/logins/new.html.erb
<h2 class="center orange-text">Login</h2>

<div class="row">
  <div class="col m4 offset-m4 center">  
    <%= form_tag '/login' do %>
      
      <div class="input-field active">
        <%= label_tag :email, "Email", class: "active" %>
        <%= text_field_tag :email %>
      </div>
      
      <div class="input-field active">
        <%= label_tag :password, "Password", class: "active" %>
        <%= password_field_tag :password %>
      </div>
      
      <%= submit_tag 'Login', class: 'btn waves-effect waves-light' %>
      
    <% end %>
  </div>
</div>

app/views/pages/about.html.erb
<h2 class="center orange-text">About</h2>

<!--Intro Card-->
<div class="row">
  <div class="col s12 m8 offset-m2 l6 offset-l3">
    <div class="card orange">
      <div class="card-content white-text about-content">
        <div class="card-title center">
          <h3>Nice to meet you!</h3>
        </div>
        
        <p>Welcome to How 2 Bee! We are a team of developers, writers, and 
        beekeepers and we're happy you found us.</p>
        
        <p>You're probably guessing that we made this site because we're 
        passionate about beekeeping. You’re right! We're addicted to honey and 
        the fascinating behavior of bees.</p>
        
        <p>But besides that, we created How 2 Bee to provide you with the most 
        recent and accurate information on beekeeping.</p>
        
        <p>Hundreds of personal beekeeping experiences are spread across the web 
        with incredibly valuable information. By collecting these personal 
        beekeeping experiences, we created this site to provide you with the 
        sequential steps to become a beekeeper. The world needs beekeepers now 
        more than ever due to the decline of honey bee populations around the 
        world.</p>
        
        <p>According to BBC, bee populations in the US declined by 23% last winter. 
        But it's not too late to help the bees and make some honey on the side.</p>
        
        <p>Beekeepers are some of the best animal caretakers in the world. And 
        let's face it - raising honey bees is rewarding. Not only are you going 
        to be enjoying delicious sweet honey and other useful byproducts, but 
        there is something endearing about watching your family of bees grow 
        from only a few hundred to a few thousand. But to make that happen, you 
        need the knowledge only expert beekeepers have accumulated. How 2 Bee spent 
        thousands of hours getting expert beekeeper knowledge into your hands.</p>
        
        <p>Beekeeping isn't an activity solely for experts. It's quite simple to 
        become a beekeeper as long as you have the guidance from the experts!</p>
        
        <p>Anyone can do beekeeping, but people often get confused when they don't 
        know a clear path on how to get started. Three simple steps will take you 
        from planning for your bees, to getting everything set up, to handling 
        them on a daily basis.</p>
        
        <p>If you've ever dreamed of making your own honey, learning about bees'
        intriguing behavior up-close, or even raising your own bee family, then 
        you should take a second to explore our 
        <%= link_to "sequential steps to become a beekeeper today!", articles_path,
                                  title: "Beekeeping Steps to Starting" %></p>
                              
        <h3 class="center">Urban Beekeeping: Even in the city?</h3>
        
        <p>People living in cities and suburban areas often believe that they can't
        become beekeepers. This is simply not true! In fact, it's the opposite! 
        Many urban beekeepers will get a greater honey yield than rural beekeepers 
        because of the minimal amount of pesticides used in cities.</p>
        
        <p>This also makes it easier to avoid problems like Colony Collapse 
        Disorder (CCD), as pesticides create a load of problems for bees. Urban 
        beekeeping can be found in Rome, Montreal, Sydney, Tokyo, Berlin, and 
        even New York (and these are only a few of the hotspots to become a 
        successful urban beekeeper nowadays).</p>
        
        <p>That's where How 2 Bee comes in. All of the information on How 2 Bee 
        was gathered from academic, governmental, or other reliable sources and 
        the content is designed to be both informative and easy-to-read. How 2 Bee 
        spent months accumulating only the best beekeeping sources to supply you 
        with the most reliable information so that you can be sure you're starting 
        beekeeping on the right track.</p>
        
        <p>How 2 Bee is wholeheartedly committed to providing you with the most 
        trustworthy beekeeping material out there, and we'll continue to do so 
        for the years to come.</p>
        
        <div class="card-action center">
          <!--Links-->
          <%= link_to "Articles", articles_path, class: "btn waves-effect waves-light grey lighten-2" %>
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<h2 class="center orange-text contact-header">We'd Like to Hear From You.</h2>

<!--First Card-->
<div class="row">
  <div class="col s12 m10 offset-m1 l8 offset-l2">
    <div class="card orange">
      <div class="card-content flow-text white-text center">
        <p>Have a beekeeping story you want to share?</p>
        <br/>
        <p>Or a question about beekeeping?</p>
        <br/>
        <p>Or even advice or useful tips to make this site more useful for you?</p>
      </div>
    </div>
  </div>
</div>

<h3 class="center orange-text contact-header"><i class="fa fa-laptop"></i> Message Us <i class="fa fa-mobile"></i></h3>
        
<!--Second Card-->
<div class="row">
  <div class="col s12 m10 offset-m1 l8 offset-l2">
    <div class="card orange">
      <div class="card-content flow-text white-text center">
        <p class="link">Send us your bee story or message via 
        <a href="https://www.facebook.com/pages/How-2-Bee/442695985906764">Facebook</a>.</p>
        <br/>
        <p>Thank you for sharing your beekeeping stories, questions, and comments 
        with us and the How 2 Bee community!</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!--<h2 class="center home-header">Beekeeping made for everyone.</h2>-->
<div class="col s12 center">
  <div class="row">
    <h2 class="center orange-text">Learn how to 
    <%= link_to "raise bees", articles_path, class: "btn-large light-green waves-effect waves-light" %>
    today.</h2>
  </div>
  
  <%= link_to video_tag("home.mp4", :controls => false, 
                            :autobuffer => true, 
                            :autoplay => true, 
                            :loop => true, 
                            :class => "responsive-video home-video"), 
                            articles_path %>
</div>

app/views/pages/legal.html.erb
<!--Intro Card-->
<div class="row">
  <div class="col s12 m10 offset-m1 l8 offset-l2">
    <div class="card orange">
      <div class="card-content white-text center">
        <div class="card-title">
          Welcome!
        </div>
        <p>Here you can find all the legal documents you need.</p>
        <%= link_to "Privacy Policy", privacy_policy_path, class: "btn waves-effect waves-light" %>
        <%= link_to "Terms of Use", terms_of_use_path, class: "btn waves-effect waves-light" %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h2>Users Here</h2>
<% @users.each do |user| %>
  <h3><%= user.username %></h3>
  <p><%= user.email %></p>
<% end %>

app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    <p> Username:</br> <%= f.text_field :username%> </p>
    <p> Email:</br> <%= f.text_field :email%> </p>
    <p> Password:</br> <%= f.password_field :password%></p>
    <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
    <%= f.submit :Signup %>
  <% end %>
  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
      <% for message_error in @user.errors.full_messages %>
        <li>* <%= message_error %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<h2>User Profile Here</h2>